### ISSUE TITLE
Query score is non-functional

### ISSUE THREAD

**Issue by cjosu** [dgidb/dgidb-v5#191]

**Comment by katiestahl** [comment]
From 10/17 dgidb meeting - 
consider making query score:
* a checkbox filter that user can select if they would like to see query score on search results (note: this could slow down user searches where this is selected due to computation time) 
* a separate utility entirely, to reduce slowdown time, not confuse users who may not know what it is

**Comment by mcannon068nw** [comment]
decision was made to not implement this in v5 interface
