### ISSUE TITLE
convert antd tables to MUI

### ISSUE THREAD

**Issue by katiestahl** [dgidb/dgidb-v5#287]
all tables in the app are antd tables, which are outdated and clunky and some features do not work (such as changing the # of results per page). we should work toward replacing these with MUI tables instead

**Comment by jsstevenson** [comment]
Outstanding questions

- [ ] how does this interact with TSV downloads for the search? If a user imposes filters on the data, does that happen clientside or serverside? If the former, how can we reflect it back into the server's view of the data (since TSV generation happens serverside)
- [ ] Are we paginating our queries, or fetching everything and paginating in the client? (Ideally the former)

**Comment by katiestahl** [comment]
> Outstanding questions
> 
> * [ ]  how does this interact with TSV downloads for the search? If a user imposes filters on the data, does that happen clientside or serverside? If the former, how can we reflect it back into the server's view of the data (since TSV generation happens serverside)
> * [ ]  Are we paginating our queries, or fetching everything and paginating in the client? (Ideally the former)

TSV downloads shouldn't be affected, as we are populating the tables with the data that gets put in the TSV. Hopefully @acoffman  can confirm

pagination should be addressed in #324
